

#
# Makefile for the Marvell Phone Device Driver Test Module
#
#

ifeq ($(CONFIG_ARCH_FEROCEON),y)
	include $(srctree)/$(MACHINE)/config/mvRules.mk
endif

obj-$(CONFIG_TDM_DEV_TEST_SUPPORT) += tdm_dev.o
